import React from 'react';
import {
    Edit3, Save, PlusCircle, List, CheckCircle, Trash2
} from 'lucide-react';

export default function CreateQuiz({
    quizTitle, setQuizTitle, classes, selectedClassIds, setSelectedClassIds,
    handleSaveQuiz, setView, currentQ, setCurrentQ, addQuestionToLocalList,
    questions, setQuestions
}) {
    return (
        <div className="min-h-screen bg-slate-50 p-6 flex justify-center font-sans items-center">
            <div className="w-full max-w-7xl bg-white rounded-[40px] shadow-2xl border border-slate-200 flex flex-col md:flex-row overflow-hidden h-[85vh]">
                <div className="md:w-1/3 bg-slate-50/50 p-10 border-r border-slate-200 flex flex-col h-full">
                    <div className="mb-8"><h2 className="text-2xl font-extrabold flex items-center gap-3 text-slate-800 mb-2"><div className="p-2.5 bg-blue-600 rounded-xl text-white shadow-lg shadow-blue-200"><Edit3 size={20} /></div> Editor Quiz</h2><p className="text-slate-500 text-sm font-medium pl-14">Konfigurasi detail ujian Anda.</p></div>
                    <div className="space-y-6 flex-1 overflow-y-auto pr-2">
                        <div className="group"><label className="text-xs font-bold text-slate-500 uppercase tracking-wide mb-2 block group-focus-within:text-blue-600 transition-colors">Judul Quiz</label><input className="w-full border border-slate-200 bg-white p-4 rounded-2xl focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 outline-none font-bold text-lg text-slate-800 transition-all placeholder:font-normal placeholder:text-slate-300" value={quizTitle} onChange={e => setQuizTitle(e.target.value)} placeholder="Contoh: PH Matematika..." /></div>
                        <div><label className="text-xs font-bold text-slate-500 uppercase tracking-wide mb-3 block">Tugaskan ke Kelas</label><div className="space-y-2 max-h-60 overflow-y-auto bg-white border border-slate-200 rounded-2xl p-3 shadow-sm">{classes.length === 0 && <div className="p-6 text-center text-xs text-slate-400 font-medium italic">Belum ada kelas dibuat.</div>}{classes.map(c => <label key={c.id} className={`flex gap-3 items-center p-3 rounded-xl cursor-pointer transition-all ${selectedClassIds.includes(c.id) ? 'bg-blue-50 border border-blue-100' : 'hover:bg-slate-50 border border-transparent'}`}><input type="checkbox" className="w-5 h-5 rounded-md text-blue-600 focus:ring-blue-500 border-slate-300" checked={selectedClassIds.includes(c.id)} onChange={e => e.target.checked ? setSelectedClassIds([...selectedClassIds, c.id]) : setSelectedClassIds(selectedClassIds.filter(id => id !== c.id))} /> <span className={`text-sm font-bold ${selectedClassIds.includes(c.id) ? 'text-blue-700' : 'text-slate-600'}`}>{c.name}</span></label>)}</div><p className="text-[10px] text-slate-400 mt-2 font-medium bg-slate-100 inline-block px-2 py-1 rounded-lg">*Kosongkan untuk akses publik via kode.</p></div>
                    </div>
                    <div className="pt-6 border-t border-slate-200 mt-auto grid gap-3"><button onClick={handleSaveQuiz} className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white py-4 rounded-2xl font-bold shadow-xl shadow-blue-200 hover:shadow-blue-300 hover:-translate-y-0.5 transition-all flex justify-center items-center gap-2 text-lg"><Save size={20} /> Simpan & Terbitkan</button><button onClick={() => setView('teacher-dash')} className="w-full text-slate-500 text-sm font-bold hover:text-slate-800 hover:bg-slate-100 py-3 rounded-xl transition">Batalkan</button></div>
                </div>
                <div className="md:w-2/3 p-10 bg-white overflow-y-auto relative">
                    <div className="mb-10 p-8 border-2 border-dashed border-blue-200 rounded-[32px] bg-blue-50/20 hover:bg-blue-50/40 transition-colors group">
                        <div className="mb-6"><label className="text-xs font-extrabold text-blue-600 uppercase mb-3 block tracking-widest">Pertanyaan Baru</label><textarea className="w-full p-5 border border-slate-200 rounded-2xl mb-4 bg-white focus:ring-4 focus:ring-blue-100 focus:border-blue-400 outline-none resize-none font-bold text-lg text-slate-800 placeholder:text-slate-300 transition-all shadow-sm group-hover:border-blue-300" rows="2" placeholder="Tulis pertanyaan di sini..." value={currentQ.question} onChange={e => setCurrentQ({ ...currentQ, question: e.target.value })} /></div>
                        <div className="grid grid-cols-2 gap-4 mb-6">{currentQ.options.map((o, i) => <div key={i} className="flex gap-3 items-center group/opt"><div onClick={() => setCurrentQ({ ...currentQ, answer: o })} className={`w-12 h-12 flex shrink-0 items-center justify-center rounded-xl cursor-pointer text-white font-bold transition-all shadow-md hover:scale-105 active:scale-95 ${currentQ.answer === o && o !== '' ? 'bg-green-500 ring-4 ring-green-100' : 'bg-slate-200 text-slate-400 hover:bg-slate-300'}`}>{String.fromCharCode(65 + i)}</div><input className={`w-full border p-3.5 rounded-xl text-sm outline-none font-medium transition-all ${currentQ.answer === o && o !== '' ? 'border-green-500 bg-green-50 text-green-800' : 'border-slate-200 focus:border-blue-400'}`} placeholder={`Pilihan ${String.fromCharCode(65 + i)}`} value={o} onChange={e => { const n = [...currentQ.options]; n[i] = e.target.value; setCurrentQ({ ...currentQ, options: n, answer: currentQ.answer === o ? e.target.value : currentQ.answer }) }} /></div>)}</div>
                        <button onClick={addQuestionToLocalList} className="w-full bg-blue-50 hover:bg-blue-100 text-blue-600 font-bold py-4 rounded-2xl text-sm transition flex items-center justify-center gap-2 border border-blue-100 hover:border-blue-200"><PlusCircle size={18} /> Tambahkan ke Daftar Soal</button>
                    </div>
                    <div className="space-y-4">{questions.length === 0 ? <div className="text-center py-20 opacity-40 select-none"><List size={64} className="mx-auto mb-4 text-slate-300" /><p className="text-lg font-bold text-slate-400">Bank soal masih kosong.</p><p className="text-sm text-slate-300">Mulai tambahkan pertanyaan di atas.</p></div> : questions.map((q, i) => <div key={i} className="bg-white border border-slate-100 p-6 rounded-[24px] flex justify-between items-start shadow-sm hover:shadow-lg hover:border-blue-200 transition-all group animate-in slide-in-from-bottom-2 duration-300"><div><div className="flex items-center gap-3 mb-2"><span className="w-8 h-8 rounded-lg bg-blue-100 text-blue-600 flex items-center justify-center font-bold text-sm">{i + 1}</span><span className="font-bold text-lg text-slate-800">{q.question}</span></div><div className="pl-11"><span className="text-xs font-bold text-green-700 bg-green-100 px-3 py-1.5 rounded-lg border border-green-200 inline-flex items-center gap-1"><CheckCircle size={12} /> Jawaban: {q.answer}</span></div></div><button onClick={() => { const n = [...questions]; n.splice(i, 1); setQuestions(n) }} className="text-slate-300 hover:text-red-500 p-3 rounded-xl hover:bg-red-50 transition"><Trash2 size={20} /></button></div>)}</div>
                </div>
            </div>
        </div>
    )
}
